<a href="https://colab.research.google.com/github/Diogo-Cardeal/PyTorch-for-DL-ML/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
 matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
matrix[0]

tensor([7, 8])

In [12]:
tensor = torch.tensor([[[1,2,3,4,5],
                        [3,6,9,4,3],
                        [2,4,5,2,8],
                        [3,4,6,5,8]]])
tensor

tensor([[[1, 2, 3, 4, 5],
         [3, 6, 9, 4, 3],
         [2, 4, 5, 2, 8],
         [3, 4, 6, 5, 8]]])

In [13]:
tensor.shape

torch.Size([1, 4, 5])

In [14]:
tensor.ndim

3

In [15]:
tensor[0, 0, 3]

tensor(4)

In [16]:
rand_tensor = torch.rand(3, 7, 3)
rand_tensor

tensor([[[0.2251, 0.7891, 0.1495],
         [0.8999, 0.4114, 0.5637],
         [0.8044, 0.7795, 0.6748],
         [0.5410, 0.5944, 0.9586],
         [0.4672, 0.7857, 0.2846],
         [0.0309, 0.8714, 0.5928],
         [0.0778, 0.1227, 0.5360]],

        [[0.5833, 0.4724, 0.5821],
         [0.4598, 0.8493, 0.0957],
         [0.1641, 0.5201, 0.2838],
         [0.0694, 0.0978, 0.3125],
         [0.0870, 0.0328, 0.2850],
         [0.1990, 0.2866, 0.1696],
         [0.2970, 0.5776, 0.8012]],

        [[0.0737, 0.7519, 0.3969],
         [0.5110, 0.6874, 0.6504],
         [0.6276, 0.1223, 0.9600],
         [0.3360, 0.8891, 0.5689],
         [0.4549, 0.5219, 0.2918],
         [0.1062, 0.2803, 0.1610],
         [0.6057, 0.3318, 0.2854]]])

In [17]:
rand_tensor.ndim

3

In [18]:
rand_img_tensor = torch.rand(size=(224, 224, 3))
rand_img_tensor.shape, rand_img_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
zeros = torch.zeros(size=(3,4)) #or torch.ones
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
rand_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [21]:
one2ten = torch.arange(1, 11)
one2ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
ten_zeros = torch.zeros_like(input=one2ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

In [23]:
float32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None,    # what datatype is the tensor (ex. float32, float16)
                              device=None,   # what device is your tensor
                              requires_grad=False) #wheter or not to track gradients with this tensor operations
float32_tensor

tensor([3., 6., 9.])

In [25]:
float32_tensor.dtype

torch.float32

In [28]:
float16_tensor = float32_tensor.type(torch.half)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float32_tensor[]


tensor(9.)

In [35]:
float16_tensor ** float32_tensor

tensor([2.7000e+01, 4.6656e+04, 3.8742e+08])