<a href="https://colab.research.google.com/github/Diogo-Cardeal/PyTorch-for-DL-ML/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
 matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[0]

tensor([7, 8])

In [ ]:
tensor = torch.tensor([[[1,2,3,4,5],
                        [3,6,9,4,3],
                        [2,4,5,2,8],
                        [3,4,6,5,8]]])
tensor

tensor([[[1, 2, 3, 4, 5],
         [3, 6, 9, 4, 3],
         [2, 4, 5, 2, 8],
         [3, 4, 6, 5, 8]]])

In [ ]:
tensor.shape

torch.Size([1, 4, 5])

In [ ]:
tensor.ndim

3

In [ ]:
tensor[0, 0, 3]

tensor(4)

In [ ]:
rand_tensor = torch.rand(3, 7, 3)
rand_tensor

tensor([[[1.1915e-01, 1.0675e-04, 9.8391e-01],
         [5.1486e-01, 2.2711e-01, 3.9435e-01],
         [4.4414e-01, 3.3976e-01, 5.0210e-01],
         [7.6775e-01, 9.0853e-01, 8.9327e-01],
         [4.0192e-01, 3.2484e-01, 7.7104e-01],
         [1.5674e-01, 9.4335e-01, 5.6536e-02],
         [4.6143e-01, 4.6118e-01, 6.8388e-01]],

        [[6.2169e-01, 2.5026e-01, 2.8123e-01],
         [6.2572e-01, 4.5506e-01, 1.6662e-01],
         [2.4201e-01, 8.2208e-01, 5.8532e-01],
         [4.0495e-01, 4.5172e-01, 1.1195e-01],
         [4.8393e-02, 6.5008e-01, 4.2184e-01],
         [4.6394e-01, 4.2367e-01, 2.0360e-01],
         [5.3322e-01, 8.8058e-01, 2.9351e-01]],

        [[8.6622e-01, 7.2629e-01, 3.3994e-01],
         [5.7266e-03, 7.7979e-01, 6.4408e-01],
         [4.2041e-01, 8.3933e-02, 9.8401e-01],
         [1.9053e-01, 7.4517e-01, 5.0110e-01],
         [8.6775e-01, 5.4593e-01, 7.0381e-01],
         [4.5130e-01, 6.4902e-01, 8.1002e-01],
         [7.4528e-01, 1.7970e-01, 2.5544e-01]]])

In [ ]:
rand_tensor.ndim

3

In [ ]:
rand_img_tensor = torch.rand(size=(224, 224, 3))
rand_img_tensor.shape, rand_img_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(size=(3,4)) #or torch.ones
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
rand_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
one2ten = torch.arange(1, 11)
one2ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one2ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

In [ ]:
float32_tensor = torch.tensor([3.0, 6.4, 9.0],
                              dtype=None,    # what datatype is the tensor (ex. float32, float16)
                              device=None,   # what device is your tensor
                              requires_grad=False) #wheter or not to track gradients with this tensor operations
float32_tensor

tensor([3.0000, 6.4000, 9.0000])

In [ ]:
float32_tensor.dtype

torch.float32

In [ ]:
float16_tensor = float32_tensor.type(torch.half)
float16_tensor

tensor([3.0000, 6.3984, 9.0000], dtype=torch.float16)

In [ ]:
float16_tensor * float32_tensor

tensor([ 9.0000, 40.9500, 81.0000])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int_32_tensor * float16_tensor

tensor([ 9.0000, 38.3750, 81.0000], dtype=torch.float16)

### Manipulating Tensors

In [ ]:
tensor1 = torch.tensor([5,2,3])

tensor1

tensor([5, 2, 3])

In [ ]:
print(tensor1)
print(f"Datatype of tensor: {tensor1.dtype}")
print(f"Shape of tensor: {tensor1.shape}")
print(f"Device tensor is on: {tensor1.device}")

tensor([5, 2, 3])
Datatype of tensor: torch.int64
Shape of tensor: torch.Size([3])
Device tensor is on: cpu


In [ ]:
# Operacoes basicas

print(tensor1 + 1)
print(tensor1 - 1)
print(tensor1 * 20)
print(tensor1 / 2)
print(tensor1 ** 2)
print(tensor1 % 2)


tensor([6, 3, 4])
tensor([4, 1, 2])
tensor([100,  40,  60])
tensor([2.5000, 1.0000, 1.5000])
tensor([25,  4,  9])
tensor([1, 0, 1])


In [ ]:
print(tensor1 * tensor1)
print(tensor1 @ tensor1)

tensor([25,  4,  9])
tensor(38)


In [ ]:
tensor2 = torch.tensor([[1, 2, 3],
                        [4, 5, 6],
                        [3, 7, 9]])
tensor3 = torch.tensor([[3, 8, 3],
                        [6, 5, 4],
                        [2, 0, 7]])
t2mm3 = torch.mm(tensor2, tensor3)

print(f"Tensor2: {tensor2}")
print(f"Tensor3: {tensor3}")
print(f"Tensor2 @ Tensor3: {t2mm3}")



Tensor2: tensor([[1, 2, 3],
        [4, 5, 6],
        [3, 7, 9]])
Tensor3: tensor([[3, 8, 3],
        [6, 5, 4],
        [2, 0, 7]])
Tensor2 @ Tensor3: tensor([[ 21,  18,  32],
        [ 54,  57,  74],
        [ 69,  59, 100]])


In [ ]:
t1 = torch.tensor([[14, 42, 93, 1, 56],
                  [16, 47, 34, 23, 100,]])
print(f"Max value: {t1.max()}")
print(f"Min value: {t1.min()}")
print(f"Mean: {t1.mean(dtype=torch.float32)}")
for i in t1:
  for index, j in enumerate(i):  # Use enumerate to get the index
    if index < len(i) - 1:  # Check if it's not the last element
      print(f"{j} + ", end="")
    else:
      print(f"{j} = ", end="")  # Print the last element without "+"
  print(f"{i.sum()}")
print(f"Total sum: {t1.sum()}")

Max value: 100
Min value: 1
Mean: 42.599998474121094
14 + 42 + 93 + 1 + 56 = 206
16 + 47 + 34 + 23 + 100 = 220
Total sum: 426


In [ ]:
print(f"The lowest value is {t1.min()} and it is located at position {t1.argmin() + 1}")
print(f"The highest value is {t1.max()} and it is located at position {t1.argmax() + 1}")


The lowest value is 1 and it is located at position 4
The highest value is 100 and it is located at position 10


In [9]:
x = torch.arange(1., 21.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20.]),
 torch.Size([20]))

In [19]:
Xreshaped = x.reshape(5, 4)
Xreshaped, Xreshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.],
         [13., 14., 15., 16.],
         [17., 18., 19., 20.]]),
 torch.Size([5, 4]))

In [28]:
z = x.view(1, 20)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
          15., 16., 17., 18., 19., 20.]]),
 torch.Size([1, 20]))

In [32]:
RANDOM_SEED = 42


torch.manual_seed(RANDOM_SEED)
ten1 = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
ten2 = torch.rand(3, 4)
print(ten1)
print(ten2)
print(ten1 == ten2)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [37]:
tensor = torch.tensor([1, 2, 3])
tensor.device

device(type='cpu')

In [38]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [43]:
Ntensor = tensor.to(device)

In [51]:
Ntensor.cpu().numpy()

array([1, 2, 3])