# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [21]:
# Import torch
import torch

# Create random tensor
tensor1 = torch.rand(7, 7)
tensor1

tensor([[0.4772, 0.5848, 0.6822, 0.2112, 0.0282, 0.6520, 0.7644],
        [0.8071, 0.6506, 0.6638, 0.4737, 0.7282, 0.0210, 0.0847],
        [0.8006, 0.2739, 0.0788, 0.2666, 0.9754, 0.9574, 0.5040],
        [0.9940, 0.7839, 0.5728, 0.9000, 0.3839, 0.5749, 0.3617],
        [0.7772, 0.1636, 0.5952, 0.1779, 0.1954, 0.8561, 0.8202],
        [0.2084, 0.5804, 0.6666, 0.8753, 0.4092, 0.9577, 0.7982],
        [0.9811, 0.0120, 0.3279, 0.1323, 0.7967, 0.2495, 0.8127]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [23]:
# Create another random tensor
tensor2 = torch.rand(1, 7)

# Perform matrix multiplication
result = tensor1 @ tensor2.T
print(result.shape)


torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [28]:
# Set manual seed
MANUAL_SEED = 0

# Create two random tensors
torch.manual_seed(MANUAL_SEED)
tensor1 = torch.rand(7, 7)

torch.manual_seed(MANUAL_SEED)
tensor2 = torch.rand(1, 7)

# Matrix multiply tensors
result = tensor1 @ tensor2.T
print(result, result.shape)


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [30]:
# Set random seed on the GPU
New_seed = 1234
torch.cuda.manual_seed(New_seed)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [34]:
# Set random seed
New_seed = 1234


# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
torch.manual_seed(New_seed)
tensor1 = torch.rand(2, 3).to(device)

torch.manual_seed(New_seed)
tensor2 = torch.rand(2, 3).to(device)
print(tensor1)
print(tensor2)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
