# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [9]:
# Import torch
import torch

# Create random tensor
a = torch.rand(7,7)
a

tensor([[0.0389, 0.8457, 0.7213, 0.2259, 0.0964, 0.5880, 0.6882],
        [0.3471, 0.1863, 0.6193, 0.1405, 0.9326, 0.4660, 0.3698],
        [0.6173, 0.9831, 0.9881, 0.7297, 0.9712, 0.3103, 0.0118],
        [0.8933, 0.7722, 0.0657, 0.8630, 0.7559, 0.2673, 0.3421],
        [0.4914, 0.7281, 0.1984, 0.0490, 0.8259, 0.8726, 0.4179],
        [0.6000, 0.0686, 0.3354, 0.6937, 0.2403, 0.8175, 0.6379],
        [0.6793, 0.7689, 0.0013, 0.8237, 0.8923, 0.6115, 0.3822]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [11]:
# Create another random tensor
b = torch.rand(1, 7)

# Perform matrix multiplication
torch.matmul(a, b.T)

tensor([[1.8380],
        [1.3438],
        [1.7438],
        [1.7521],
        [1.9260],
        [1.6265],
        [1.9928]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [12]:
# Set manual seed
manual_seed = 0

# Create two random tensors
a = torch.rand(7,7)
b = torch.rand(1, 7)

# Matrix multiply tensors
torch.matmul(a, b.T)

tensor([[2.6962],
        [1.8003],
        [1.3569],
        [2.9150],
        [2.0176],
        [3.1135],
        [2.1649]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [13]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [14]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
a = torch.rand(2,3).to(device)
b = torch.rand(2,3).to(device)
a, b

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [23]:
# Perform matmul on tensor_A and tensor_B
c =a @ b.T
c

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [20]:
# Find max
print(f"Max: {torch.max(c)}")
# Find min
print(f"Min: {torch.min(c)}")



Max: 0.5617256760597229
Min: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [21]:
# Find arg max
print(f"Max: {torch.argmax(c)}")

# Find arg min
print(f"Min: {torch.argmin(c)}")

Max: 3
Min: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [25]:
# Set seed
torch.manual_seed(7)

# Create random tensor
a = torch.rand(1, 1, 1, 10)
print(f"Tensor: {a}")
print(f"Shape: {a.shape}")

# Remove single dimensions
a = torch.squeeze(torch.rand(1, 1, 1, 10))


# Print out tensors and their shapes
print(f"Tensor: {a}")
print(f"Shape: {a.shape}")

Tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape: torch.Size([1, 1, 1, 10])
Tensor: tensor([0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204, 0.0731, 0.9699,
        0.1078])
Shape: torch.Size([10])
